"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.readDirWithPath = exports.readDirEnts = void 0;
const fs_1 = require("fs");
const path_1 = require("path");
const readDirEnts = (dir) => fs_1.readdirSync(dir, { withFileTypes: true });
exports.readDirEnts = readDirEnts;
;
;
const readDirWithPath = (dir) => exports.readDirEnts(dir).map((entry) => Object.assign(entry, { path: path_1.resolve(dir, entry.name) }));
exports.readDirWithPath = readDirWithPath;
